### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [tc/pig-latin-tmbundle#1]
I would like to use your grammar for PigLatin but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@tc Did you get a chance to look into this? I'm considering using your grammar at [github/linguist](https://github.com/github/linguist) to highlight PigLatin code on GitHub.

**Comment by tc** [comment]
hi yes, i'll add an MIT license

On Sat, Feb 7, 2015 at 5:05 AM, Paul Chaignon notifications@github.com
wrote:

> @tc https://github.com/tc Did you get a chance to look into this? I'm
> considering using your grammar at github/linguist
> https://github.com/github/linguist to highlight PigLatin code on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tc/pig-latin-tmbundle/issues/1#issuecomment-73363486.

## 

Tommy Chheng

**Comment by pchaigno** [comment]
Thanks!
